FROM node:22

# Instalar dependências de fontes
RUN apt-get update && apt-get install -y \
  fontconfig \
  fonts-freefont-ttf \
  && rm -rf /var/lib/apt/lists/*

# Configurar o diretório da aplicação
WORKDIR /app

# Copiar arquivos da aplicação
COPY package.json package-lock.json ./
RUN npm install
COPY . .

# Expor a porta e iniciar o servidor
EXPOSE 3000
CMD ["npm", "start"]